# Introduction {#intro}

## Overview of the Study

From the resource-based theory perspective, knowledge is considered one of a company's most important strategic resources.
[@Grant1997] Scholars have conducted numerous studies on the relationship between the employee's motivation for knowledge sharing and employee creativity.
Many scholars have suggested that the employee's motivation for knowledge sharing can promote employee creativity at the individual level.
The most critical factor for this promotion is knowledge transformation.
[@Perry2006, @Watson2006]

## Significant of the Study

Some scholars have made valuable additions to knowledge sharing in business in developing research on knowledge sharing.
The literature review concludes that the process of the individual contribution of knowledge to the organization is a cooperative contribution, and the use of public knowledge is non-exclusive and non-competitive, which are characteristics of "public goods." They construct an economic model using mathematical methods to explain the process of knowledge sharing.
[@Bhattacharya1998, @Cabrera1996]

## Objectives of the Study

Some scholars have made valuable additions to knowledge sharing in business in developing research on knowledge sharing[@Allameh2018].

## Contribution of the Study

Some scholars have made valuable additions to knowledge sharing in business in developing research on knowledge sharing.

## Limitation of the Study

Some scholars have made valuable additions to knowledge sharing in business in developing research on knowledge sharing[@Baas2013].

## Terms and Definition Used in This Study

Some scholars have made valuable additions to knowledge sharing in business in developing research on knowledge sharing.

\newpage
