# Conclusion and Recommendation {#conclusions}


## Discussion

The perceived level of the employee's motivation for knowledge sharing in this study is at an agreed level. The result is the same as that of most related literature, such as Zhao Shusong [@Zhao2011] studied the influence of the employee's motivation for knowledge sharing and performance appraisal on individual knowledge-sharing behavior. All of the subjects worked in high-tech companies. The result showed an agreed level of the employee's motivation for knowledge sharing. 

## Conclusion

Wang Chenchen [@Wang2014] studied the relationship between the employee's motivation for knowledge sharing and service innovation performance of high-end hotels in different provinces of China. The study statistics indicated that the employee's motivation for knowledge sharing was at an agreed level. Liu Shujing [@Liu2012] studied the relationship between reciprocal preference, employee engagement, and the employee's motivation for knowledge sharing in different types of enterprises. The result showed an agreed level of the employee's motivation for knowledge sharing. Yu Xiaohua [@Yu2018] studied the influence mechanism between the employee's motivation for knowledge sharing and the individual creativity of new-generation knowledge employees. All subjects were post-80s from manufacturing, finance, insurance, real estate, electronic technology, etc. The result showed that the employee's motivation for knowledge-sharing was at an agreed level.


\newpage